// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package turso_models

import (
	"context"
)

const deleteDocumentByID = `-- name: DeleteDocumentByID :exec
DELETE FROM documents
WHERE id = ?
`

func (q *Queries) DeleteDocumentByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentByID, id)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, status, payload, title, created_at_ms, updated_at_ms, deleted_at_ms FROM documents
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Payload,
		&i.Title,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
		&i.DeletedAtMs,
	)
	return i, err
}

const listDocumentsRecent = `-- name: ListDocumentsRecent :many
SELECT id, status, payload, title, created_at_ms, updated_at_ms, deleted_at_ms FROM documents
WHERE deleted_at_ms IS NULL
ORDER BY updated_at_ms DESC
LIMIT ?
`

func (q *Queries) ListDocumentsRecent(ctx context.Context, limit int64) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsRecent, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Payload,
			&i.Title,
			&i.CreatedAtMs,
			&i.UpdatedAtMs,
			&i.DeletedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocument = `-- name: UpsertDocument :exec
INSERT INTO documents (id, status, payload)
VALUES (?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  status = excluded.status,
  payload = excluded.payload,
  deleted_at_ms = NULL
`

type UpsertDocumentParams struct {
	ID      string `json:"id"`
	Status  string `json:"status"`
	Payload string `json:"payload"`
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error {
	_, err := q.db.ExecContext(ctx, upsertDocument, arg.ID, arg.Status, arg.Payload)
	return err
}
