// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: healthcheck.sql

package turso_models

import (
	"context"
)

const tursoHealthcheck = `-- name: TursoHealthcheck :one
SELECT 1 AS ok
`

func (q *Queries) TursoHealthcheck(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, tursoHealthcheck)
	var ok int64
	err := row.Scan(&ok)
	return ok, err
}
