// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package turso_models

import (
	"database/sql"
)

type Document struct {
	ID          string         `json:"id"`
	Status      string         `json:"status"`
	Payload     string         `json:"payload"`
	Title       sql.NullString `json:"title"`
	CreatedAtMs int64          `json:"created_at_ms"`
	UpdatedAtMs int64          `json:"updated_at_ms"`
	DeletedAtMs interface{}    `json:"deleted_at_ms"`
}

type GooseDbVersion struct {
	ID        int64        `json:"id"`
	VersionID int64        `json:"version_id"`
	IsApplied int64        `json:"is_applied"`
	Tstamp    sql.NullTime `json:"tstamp"`
}
