// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stocks.sql

package turso_models

import (
	"context"
)

const getPublishedStockDetail = `-- name: GetPublishedStockDetail :one
SELECT ticker, report_id, stock_detail, published_at_ms, updated_at_ms FROM published_stock_details
WHERE ticker = ?
LIMIT 1
`

func (q *Queries) GetPublishedStockDetail(ctx context.Context, ticker string) (PublishedStockDetail, error) {
	row := q.db.QueryRowContext(ctx, getPublishedStockDetail, ticker)
	var i PublishedStockDetail
	err := row.Scan(
		&i.Ticker,
		&i.ReportID,
		&i.StockDetail,
		&i.PublishedAtMs,
		&i.UpdatedAtMs,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT ticker, status, created_at_ms, updated_at_ms FROM subscriptions
WHERE ticker = ?
LIMIT 1
`

func (q *Queries) GetSubscription(ctx context.Context, ticker string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscription, ticker)
	var i Subscription
	err := row.Scan(
		&i.Ticker,
		&i.Status,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
	)
	return i, err
}

const insertStockReport = `-- name: InsertStockReport :exec
INSERT INTO stock_reports (id, ticker, r2_key, provenance, published_at_ms)
VALUES (?, ?, ?, ?, ?)
`

type InsertStockReportParams struct {
	ID            string `json:"id"`
	Ticker        string `json:"ticker"`
	R2Key         string `json:"r2_key"`
	Provenance    string `json:"provenance"`
	PublishedAtMs int64  `json:"published_at_ms"`
}

func (q *Queries) InsertStockReport(ctx context.Context, arg InsertStockReportParams) error {
	_, err := q.db.ExecContext(ctx, insertStockReport,
		arg.ID,
		arg.Ticker,
		arg.R2Key,
		arg.Provenance,
		arg.PublishedAtMs,
	)
	return err
}

const listActiveSubscriptions = `-- name: ListActiveSubscriptions :many
SELECT ticker, status, created_at_ms, updated_at_ms FROM subscriptions
WHERE status = 'active'
ORDER BY ticker ASC
`

func (q *Queries) ListActiveSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.Ticker,
			&i.Status,
			&i.CreatedAtMs,
			&i.UpdatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedStockDetails = `-- name: ListPublishedStockDetails :many
SELECT ticker, report_id, stock_detail, published_at_ms, updated_at_ms FROM published_stock_details
ORDER BY updated_at_ms DESC
`

func (q *Queries) ListPublishedStockDetails(ctx context.Context) ([]PublishedStockDetail, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedStockDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublishedStockDetail
	for rows.Next() {
		var i PublishedStockDetail
		if err := rows.Scan(
			&i.Ticker,
			&i.ReportID,
			&i.StockDetail,
			&i.PublishedAtMs,
			&i.UpdatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockReportsByTicker = `-- name: ListStockReportsByTicker :many
SELECT id, ticker, r2_key, provenance, published_at_ms, created_at_ms FROM stock_reports
WHERE ticker = ?
ORDER BY published_at_ms DESC
`

func (q *Queries) ListStockReportsByTicker(ctx context.Context, ticker string) ([]StockReport, error) {
	rows, err := q.db.QueryContext(ctx, listStockReportsByTicker, ticker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockReport
	for rows.Next() {
		var i StockReport
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.R2Key,
			&i.Provenance,
			&i.PublishedAtMs,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPublishedStockDetail = `-- name: UpsertPublishedStockDetail :exec
INSERT INTO published_stock_details (ticker, report_id, stock_detail, published_at_ms)
VALUES (?, ?, ?, ?)
ON CONFLICT(ticker) DO UPDATE SET
  report_id       = excluded.report_id,
  stock_detail    = excluded.stock_detail,
  published_at_ms = excluded.published_at_ms,
  updated_at_ms   = (unixepoch('now') * 1000)
`

type UpsertPublishedStockDetailParams struct {
	Ticker        string `json:"ticker"`
	ReportID      string `json:"report_id"`
	StockDetail   string `json:"stock_detail"`
	PublishedAtMs int64  `json:"published_at_ms"`
}

func (q *Queries) UpsertPublishedStockDetail(ctx context.Context, arg UpsertPublishedStockDetailParams) error {
	_, err := q.db.ExecContext(ctx, upsertPublishedStockDetail,
		arg.Ticker,
		arg.ReportID,
		arg.StockDetail,
		arg.PublishedAtMs,
	)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (ticker, status)
VALUES (?, ?)
ON CONFLICT(ticker) DO UPDATE SET
  status = excluded.status,
  updated_at_ms = (unixepoch('now') * 1000)
`

type UpsertSubscriptionParams struct {
	Ticker string `json:"ticker"`
	Status string `json:"status"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSubscription, arg.Ticker, arg.Status)
	return err
}
