// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stocks.sql

package turso_models

import (
	"context"
)

const getPublishedStockDetail = `-- name: GetPublishedStockDetail :one
SELECT ticker, report_id, r2_report_key, r2_detail_key, r2_detail_zh_tw_key, summary_json, summary_json_zh_tw, published_at_ms, updated_at_ms FROM published_stock_details
WHERE ticker = ?
LIMIT 1
`

func (q *Queries) GetPublishedStockDetail(ctx context.Context, ticker string) (PublishedStockDetail, error) {
	row := q.db.QueryRowContext(ctx, getPublishedStockDetail, ticker)
	var i PublishedStockDetail
	err := row.Scan(
		&i.Ticker,
		&i.ReportID,
		&i.R2ReportKey,
		&i.R2DetailKey,
		&i.R2DetailZhTwKey,
		&i.SummaryJson,
		&i.SummaryJsonZhTw,
		&i.PublishedAtMs,
		&i.UpdatedAtMs,
	)
	return i, err
}

const getStockReportByTickerAndID = `-- name: GetStockReportByTickerAndID :one
SELECT id, ticker, r2_key, r2_detail_key, r2_detail_zh_tw_key, summary_json, summary_json_zh_tw, provenance, published_at_ms, created_at_ms FROM stock_reports
WHERE ticker = ? AND id = ?
LIMIT 1
`

type GetStockReportByTickerAndIDParams struct {
	Ticker string `json:"ticker"`
	ID     string `json:"id"`
}

func (q *Queries) GetStockReportByTickerAndID(ctx context.Context, arg GetStockReportByTickerAndIDParams) (StockReport, error) {
	row := q.db.QueryRowContext(ctx, getStockReportByTickerAndID, arg.Ticker, arg.ID)
	var i StockReport
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.R2Key,
		&i.R2DetailKey,
		&i.R2DetailZhTwKey,
		&i.SummaryJson,
		&i.SummaryJsonZhTw,
		&i.Provenance,
		&i.PublishedAtMs,
		&i.CreatedAtMs,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT ticker, status, created_at_ms, updated_at_ms FROM subscriptions
WHERE ticker = ?
LIMIT 1
`

func (q *Queries) GetSubscription(ctx context.Context, ticker string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscription, ticker)
	var i Subscription
	err := row.Scan(
		&i.Ticker,
		&i.Status,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
	)
	return i, err
}

const getTechnicalSnapshotByTickerAndReportID = `-- name: GetTechnicalSnapshotByTickerAndReportID :one
SELECT ticker, report_id, status, source, provider, r2_snapshot_key, r2_snapshot_zh_tw_key, error_message, published_at_ms, updated_at_ms FROM technical_snapshots
WHERE ticker = ? AND report_id = ?
LIMIT 1
`

type GetTechnicalSnapshotByTickerAndReportIDParams struct {
	Ticker   string `json:"ticker"`
	ReportID string `json:"report_id"`
}

func (q *Queries) GetTechnicalSnapshotByTickerAndReportID(ctx context.Context, arg GetTechnicalSnapshotByTickerAndReportIDParams) (TechnicalSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getTechnicalSnapshotByTickerAndReportID, arg.Ticker, arg.ReportID)
	var i TechnicalSnapshot
	err := row.Scan(
		&i.Ticker,
		&i.ReportID,
		&i.Status,
		&i.Source,
		&i.Provider,
		&i.R2SnapshotKey,
		&i.R2SnapshotZhTwKey,
		&i.ErrorMessage,
		&i.PublishedAtMs,
		&i.UpdatedAtMs,
	)
	return i, err
}

const insertStockReport = `-- name: InsertStockReport :exec
INSERT INTO stock_reports (
  id,
  ticker,
  r2_key,
  r2_detail_key,
  r2_detail_zh_tw_key,
  summary_json,
  summary_json_zh_tw,
  provenance,
  published_at_ms
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertStockReportParams struct {
	ID              string `json:"id"`
	Ticker          string `json:"ticker"`
	R2Key           string `json:"r2_key"`
	R2DetailKey     string `json:"r2_detail_key"`
	R2DetailZhTwKey string `json:"r2_detail_zh_tw_key"`
	SummaryJson     string `json:"summary_json"`
	SummaryJsonZhTw string `json:"summary_json_zh_tw"`
	Provenance      string `json:"provenance"`
	PublishedAtMs   int64  `json:"published_at_ms"`
}

func (q *Queries) InsertStockReport(ctx context.Context, arg InsertStockReportParams) error {
	_, err := q.db.ExecContext(ctx, insertStockReport,
		arg.ID,
		arg.Ticker,
		arg.R2Key,
		arg.R2DetailKey,
		arg.R2DetailZhTwKey,
		arg.SummaryJson,
		arg.SummaryJsonZhTw,
		arg.Provenance,
		arg.PublishedAtMs,
	)
	return err
}

const listActiveSubscriptions = `-- name: ListActiveSubscriptions :many
SELECT ticker, status, created_at_ms, updated_at_ms FROM subscriptions
WHERE status = 'active'
ORDER BY ticker ASC
`

func (q *Queries) ListActiveSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.Ticker,
			&i.Status,
			&i.CreatedAtMs,
			&i.UpdatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedStockDetails = `-- name: ListPublishedStockDetails :many
SELECT ticker, report_id, r2_report_key, r2_detail_key, r2_detail_zh_tw_key, summary_json, summary_json_zh_tw, published_at_ms, updated_at_ms FROM published_stock_details
ORDER BY updated_at_ms DESC
`

func (q *Queries) ListPublishedStockDetails(ctx context.Context) ([]PublishedStockDetail, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedStockDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublishedStockDetail
	for rows.Next() {
		var i PublishedStockDetail
		if err := rows.Scan(
			&i.Ticker,
			&i.ReportID,
			&i.R2ReportKey,
			&i.R2DetailKey,
			&i.R2DetailZhTwKey,
			&i.SummaryJson,
			&i.SummaryJsonZhTw,
			&i.PublishedAtMs,
			&i.UpdatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockReportsByTicker = `-- name: ListStockReportsByTicker :many
SELECT id, ticker, r2_key, r2_detail_key, r2_detail_zh_tw_key, summary_json, summary_json_zh_tw, provenance, published_at_ms, created_at_ms FROM stock_reports
WHERE ticker = ?
  AND summary_json != '{}'
  AND r2_detail_key != ''
ORDER BY published_at_ms DESC
`

func (q *Queries) ListStockReportsByTicker(ctx context.Context, ticker string) ([]StockReport, error) {
	rows, err := q.db.QueryContext(ctx, listStockReportsByTicker, ticker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockReport
	for rows.Next() {
		var i StockReport
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.R2Key,
			&i.R2DetailKey,
			&i.R2DetailZhTwKey,
			&i.SummaryJson,
			&i.SummaryJsonZhTw,
			&i.Provenance,
			&i.PublishedAtMs,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPublishedStockDetail = `-- name: UpsertPublishedStockDetail :exec
INSERT INTO published_stock_details (
  ticker,
  report_id,
  r2_report_key,
  r2_detail_key,
  r2_detail_zh_tw_key,
  summary_json,
  summary_json_zh_tw,
  published_at_ms
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(ticker) DO UPDATE SET
  report_id          = excluded.report_id,
  r2_report_key      = excluded.r2_report_key,
  r2_detail_key      = excluded.r2_detail_key,
  r2_detail_zh_tw_key = excluded.r2_detail_zh_tw_key,
  summary_json       = excluded.summary_json,
  summary_json_zh_tw = excluded.summary_json_zh_tw,
  published_at_ms    = excluded.published_at_ms,
  updated_at_ms      = (unixepoch('now') * 1000)
`

type UpsertPublishedStockDetailParams struct {
	Ticker          string `json:"ticker"`
	ReportID        string `json:"report_id"`
	R2ReportKey     string `json:"r2_report_key"`
	R2DetailKey     string `json:"r2_detail_key"`
	R2DetailZhTwKey string `json:"r2_detail_zh_tw_key"`
	SummaryJson     string `json:"summary_json"`
	SummaryJsonZhTw string `json:"summary_json_zh_tw"`
	PublishedAtMs   int64  `json:"published_at_ms"`
}

func (q *Queries) UpsertPublishedStockDetail(ctx context.Context, arg UpsertPublishedStockDetailParams) error {
	_, err := q.db.ExecContext(ctx, upsertPublishedStockDetail,
		arg.Ticker,
		arg.ReportID,
		arg.R2ReportKey,
		arg.R2DetailKey,
		arg.R2DetailZhTwKey,
		arg.SummaryJson,
		arg.SummaryJsonZhTw,
		arg.PublishedAtMs,
	)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (ticker, status)
VALUES (?, ?)
ON CONFLICT(ticker) DO UPDATE SET
  status = excluded.status,
  updated_at_ms = (unixepoch('now') * 1000)
`

type UpsertSubscriptionParams struct {
	Ticker string `json:"ticker"`
	Status string `json:"status"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSubscription, arg.Ticker, arg.Status)
	return err
}

const upsertTechnicalSnapshot = `-- name: UpsertTechnicalSnapshot :exec
INSERT INTO technical_snapshots (
  ticker,
  report_id,
  status,
  source,
  provider,
  r2_snapshot_key,
  r2_snapshot_zh_tw_key,
  error_message,
  published_at_ms
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(ticker, report_id) DO UPDATE SET
  status                = excluded.status,
  source                = excluded.source,
  provider              = excluded.provider,
  r2_snapshot_key       = excluded.r2_snapshot_key,
  r2_snapshot_zh_tw_key = excluded.r2_snapshot_zh_tw_key,
  error_message         = excluded.error_message,
  published_at_ms       = excluded.published_at_ms,
  updated_at_ms         = (unixepoch('now') * 1000)
`

type UpsertTechnicalSnapshotParams struct {
	Ticker            string `json:"ticker"`
	ReportID          string `json:"report_id"`
	Status            string `json:"status"`
	Source            string `json:"source"`
	Provider          string `json:"provider"`
	R2SnapshotKey     string `json:"r2_snapshot_key"`
	R2SnapshotZhTwKey string `json:"r2_snapshot_zh_tw_key"`
	ErrorMessage      string `json:"error_message"`
	PublishedAtMs     int64  `json:"published_at_ms"`
}

func (q *Queries) UpsertTechnicalSnapshot(ctx context.Context, arg UpsertTechnicalSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertTechnicalSnapshot,
		arg.Ticker,
		arg.ReportID,
		arg.Status,
		arg.Source,
		arg.Provider,
		arg.R2SnapshotKey,
		arg.R2SnapshotZhTwKey,
		arg.ErrorMessage,
		arg.PublishedAtMs,
	)
	return err
}
