FROM golang:1.25.0 AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/worker ./cmd/worker

FROM gcr.io/distroless/static-debian12

WORKDIR /app

COPY --from=builder /out/worker /app/worker

ENTRYPOINT ["/app/worker"]
